version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: sh start
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
  db:
    image: 'postgres:12'
    environment:
      POSTGRES_USER: ridecotest
      POSTGRES_DB: ridecotest
      POSTGRES_PASSWORD: Rid3cotest123.
    volumes:
      - .pgdata:/var/lib/posgresql/data
    ports:
      - "5432:5432"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/frontend_app
      - /app/node_modules
    command: npm run dev
