# Generated by Django 3.2.4 on 2022-03-30 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_item_grocery_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='grocery_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='grocery_list.grocerylist'),
        ),
    ]
